from enum import StrEnum


class EventType(StrEnum):
    MARKET_TICK_RECEIVED = "MARKET_TICK_RECEIVED"
    ORDER_BOOK_UPDATED = "ORDER_BOOK_UPDATED"
    GRID_REBALANCED = "GRID_REBALANCED"
    LEVEL_FILLED = "LEVEL_FILLED"
    LEVEL_REPLENISHED = "LEVEL_REPLENISHED"
